name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Cotinous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **.py
            README.md
  
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: action/download-artifact@v4
        with:
          name: projetozipado
      - name: Display Structure of downloaded files
        run: ls -R